<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Photo;

class PhotoTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Photo::truncate();

        Photo::insert([
            ['image' => 'img/photos/1.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/3.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/6.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/9.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/10.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/11.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/13.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/14.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/16.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/17.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/21.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/23.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/26.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/27.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/28.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/30.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/32.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/33.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/34.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/37.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/41.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/44.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/45.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/47.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/49.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/50.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/51.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/51.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/52.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/53.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/54.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/55.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/58.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/59.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/62.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/63.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/64.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/68.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/70.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/73.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/74.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/75.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/77.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/78.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/81.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/82.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/83.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/84.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/85.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/87.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/88.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/89.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/93.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/94.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/95.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/96.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/98.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/100.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/101.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/102.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/103.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/104.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/105.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/106.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/107.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/110.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/112.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/113.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/114.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/117.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/119.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/120.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/128.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/129.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/130.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/131.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/132.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/133.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/134.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/135.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/136.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/137.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/138.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/201.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/203.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/204.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/205.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/206.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/207.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/208.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/209.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/300.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/302.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/303.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/304.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/305.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/309.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/310.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/311.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/312.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/313.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/314.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/315.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/316.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/317.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/318.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/320.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/321.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/322.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/323.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/324.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/325.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/326.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/327.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/328.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/329.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/330.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/331.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/332.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/333.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/334.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/335.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/336.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/337.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/338.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/339.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/340.jpg', 'description' => 'description comes here'],
            ['image' => 'img/photos/mt-sample-background.jpg', 'description' => 'description comes here'],
        ]);
    }
}
