<?php

namespace App\Doctrine\Types;

use Doctrine\DBAL\Types\Type;
use Doctrine\DBAL\Platforms\AbstractPlatform;

class EnumType extends Type
{
    protected $name = 'enum';

    public function getSQLDeclaration(array $fieldDeclaration, AbstractPlatform $platform)
    {
        // TODO: Implement getSQLDeclaration() method.
        return "ENUM('" . implode("', '", $fieldDeclaration['allowed']) . "')";
    }

    public function convertToPHPValue($value, AbstractPlatform $platform)
    {
        return $value; // TODO: Change the autogenerated stub
    }

    public function getName()
    {
        return $this->name; // TODO: Implement getName() method.
    }

    public function requiresSQLCommentHint(AbstractPlatform $platform)
    {
        return true; // TODO: Change the autogenerated stub
    }
}
