<?php

return [
    ['name' => 'Внеземная жизнь', 'slug' => 'vnezemnaya-zhizn',],
    ['name' => 'Вселенная', 'slug' => 'vselennaya',],
    ['name' => 'Интеллект и Сознание', 'slug' => 'intellekt-i-soznanie',],
    ['name' => 'Искусственный интеллект', 'slug' => 'iskusstvennyi-intellekt',],
    ['name' => 'История жизни на Земле', 'slug' => 'istoriya-zhizni-na-zemle',],
    ['name' => 'Квантовая физика', 'slug' => 'kvantovaya-fizika',],
    ['name' => 'Основа бытия', 'slug' => 'osnova-bytiya',],
    ['name' => 'Предрассудок', 'slug' => 'predrassudok',],
    ['name' => 'Природа человека', 'slug' => 'priroda-cheloveka',],
    ['name' => 'Футурология', 'slug' => 'futurologiya',],
    ['name' => 'Вера в человека', 'slug' => 'vera-v-cheloveka',],
    ['name' => 'Наставничество', 'slug' => 'nastavnichestvo',],
    ['name' => 'Образование', 'slug' => 'obrazovanie',],
    ['name' => 'Опасности и Риски', 'slug' => 'opasnosti-i-riski',],
    ['name' => 'Популяризация науки', 'slug' => 'populyarizaciya-nauki',],
    ['name' => 'Предпринимательство', 'slug' => 'predprinimatelstvo',],
    ['name' => 'Руководитель', 'slug' => 'rukovoditeli',],
    ['name' => 'Творчество', 'slug' => 'tvorchestvo',],
    ['name' => 'Технология', 'slug' => 'tehnologiya',],
    ['name' => 'Цивилизация', 'slug' => 'civilizaciya',],
    ['name' => 'Экономика и Политика', 'slug' => 'ekonomika-i-politika',],
    ['name' => 'Достижения и Упорство', 'slug' => 'dostizheniya-i-uporstvo',],
    ['name' => 'Здоровый образ жизни', 'slug' => 'zdorovyi-obraz-zhizni',],
    ['name' => 'Компетентность', 'slug' => 'kompetentnost',],
    ['name' => 'Любовь к жизни', 'slug' => 'ljubov-k-zhizni',],
    ['name' => 'Мировоззрение', 'slug' => 'mirovozzrenie',],
    ['name' => 'Мораль и Ответственность', 'slug' => 'moral-i-otvetstvennost',],
    ['name' => 'Предостережение', 'slug' => 'predosterezhenie',],
    ['name' => 'Развитие личности', 'slug' => 'razvitie-lichnosti',],
    ['name' => 'Самоконтроль', 'slug' => 'samokontrol',],
    ['name' => 'Смысл жизни и Счастье', 'slug' => 'smysl-zhizni-i-schaste',],
    ['name' => 'Социальная среда', 'slug' => 'socialnaya-sreda',],
    ['name' => 'Способности и Ресурсы', 'slug' => 'sposobnosti-i-resursy',],
    ['name' => 'Уверенность в себе', 'slug' => 'uverennost-v-sebe',],
    ['name' => 'Эмоциональный интеллект', 'slug' => 'emocionalnyi-intellekt',],
    ['name' => 'Эрудиция', 'slug' => 'erudiciya',],
];
