<?php

return [
    [ 'name' => 'Внеземная жизнь', 'slug' => 'vnezemnaya-zhizn', ],
    [ 'name' => 'Вселенная и Космология', 'slug' => 'vselennaya-i-kosmologiya', ],
    [ 'name' => 'Интеллект и Сознание', 'slug' => 'intellekt-i-soznanie', ],
    [ 'name' => 'История жизни на Земле', 'slug' => 'istoriya-zhizni-na-zemle', ],
    [ 'name' => 'Основа бытия', 'slug' => 'osnova-bytiya', ],
    [ 'name' => 'Предрассудок', 'slug' => 'predrassudok', ],
    [ 'name' => 'Футурология', 'slug' => 'futurologiya', ],
    [ 'name' => 'Идеал и Оптимизм', 'slug' => 'ideal-i-optimizm', ],
    [ 'name' => 'Наставничество', 'slug' => 'nastavnichestvo', ],
    [ 'name' => 'Образование', 'slug' => 'obrazovanie', ],
    [ 'name' => 'Опасности и Риски', 'slug' => 'opasnosti-i-riski', ],
    [ 'name' => 'Популяризация науки', 'slug' => 'populjarizaciya-nauki', ],
    [ 'name' => 'Предпринимательство', 'slug' => 'predprinimatelstvo', ],
    [ 'name' => 'Руководитель', 'slug' => 'rukovoditeli', ],
    [ 'name' => 'Творчество', 'slug' => 'tvorchestvo', ],
    [ 'name' => 'Технология', 'slug' => 'tehnologiya', ],
    [ 'name' => 'Цивилизация', 'slug' => 'civilizaciya', ],
    [ 'name' => 'Достижения и Твёрдость', 'slug' => 'dostizheniya-i-tverdost', ],
    [ 'name' => 'Здоровый образ жизни', 'slug' => 'zdorovyi-obraz-zhizni', ],
    [ 'name' => 'Компетентность', 'slug' => 'kompetentnost', ],
    [ 'name' => 'Любовь к жизни', 'slug' => 'ljubov-k-zhizni', ],
    [ 'name' => 'Мировоззрение', 'slug' => 'mirovozzrenie', ],
    [ 'name' => 'Мораль и Ответственность', 'slug' => 'moral-i-otvetstvennost', ],
    [ 'name' => 'Окружение и Общение', 'slug' => 'okruzhenie-i-obshhenie', ],
    [ 'name' => 'Предостережение', 'slug' => 'predosterezhenie', ],
    [ 'name' => 'Развитие личности', 'slug' => 'razvitie-lichnosti', ],
    [ 'name' => 'Самоконтроль', 'slug' => 'samokontrol', ],
    [ 'name' => 'Смысл жизни и Счастье', 'slug' => 'smysl-zhizni-i-schaste', ],
    [ 'name' => 'Способности и Ресурсы', 'slug' => 'sposobnosti-i-resursy', ],
    [ 'name' => 'Уверенность в себе', 'slug' => 'uverennost-v-sebe', ],
    [ 'name' => 'Эмоциональный интеллект', 'slug' => 'emocionalnyi-intellekt', ],
    [ 'name' => 'Эрудиция', 'slug' => 'erudiciya', ],
];